//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inExpendDetail
    {
        public long IDDetail { get; set; }
        public long IDExpend { get; set; }
        public int IDProduct { get; set; }
        public int Volume { get; set; }
        public decimal BuyPrice { get; set; }
        public decimal SellPrice { get; set; }
        public decimal BuyAmount { get; set; }
        public decimal SellAmount { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
    }
}
