//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCompany.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyEntities : DbContext
    {
        public MyEntities()
            : base("name=MyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblSupplier> tblSupplier { get; set; }
        public virtual DbSet<tblSupplierContact> tblSupplierContact { get; set; }
        public virtual DbSet<tblPartner> tblPartner { get; set; }
        public virtual DbSet<View_Expend> View_Expend { get; set; }
        public virtual DbSet<View_UserAssignCampaign> View_UserAssignCampaign { get; set; }
        public virtual DbSet<View_UserAssignMenu> View_UserAssignMenu { get; set; }
        public virtual DbSet<View_PurchaseDetail> View_PurchaseDetail { get; set; }
        public virtual DbSet<inPurchaseDetail> inPurchaseDetail { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<View_Purchase> View_Purchase { get; set; }
        public virtual DbSet<View_Partner> View_Partner { get; set; }
        public virtual DbSet<inExpend> inExpend { get; set; }
        public virtual DbSet<inPurchase> inPurchase { get; set; }
        public virtual DbSet<tblProduct> tblProduct { get; set; }
        public virtual DbSet<inExpendDetail> inExpendDetail { get; set; }
        public virtual DbSet<View_Product> View_Product { get; set; }
        public virtual DbSet<View_ExpendDetail> View_ExpendDetail { get; set; }
    
        public virtual ObjectResult<SP_Partner_Result> SP_Partner(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Partner_Result>("SP_Partner", userIDParameter);
        }
    
        public virtual ObjectResult<SP_Product_Result> SP_Product(Nullable<int> campaignID)
        {
            var campaignIDParameter = campaignID.HasValue ?
                new ObjectParameter("CampaignID", campaignID) :
                new ObjectParameter("CampaignID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Product_Result>("SP_Product", campaignIDParameter);
        }
    
        public virtual ObjectResult<SP_Expend_Result> SP_Expend(Nullable<int> campaignID, Nullable<int> custCampaignID)
        {
            var campaignIDParameter = campaignID.HasValue ?
                new ObjectParameter("CampaignID", campaignID) :
                new ObjectParameter("CampaignID", typeof(int));
    
            var custCampaignIDParameter = custCampaignID.HasValue ?
                new ObjectParameter("CustCampaignID", custCampaignID) :
                new ObjectParameter("CustCampaignID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Expend_Result>("SP_Expend", campaignIDParameter, custCampaignIDParameter);
        }
    
        public virtual ObjectResult<SP_Purchase_Result> SP_Purchase(Nullable<int> campaignID, Nullable<int> custCampaignID)
        {
            var campaignIDParameter = campaignID.HasValue ?
                new ObjectParameter("CampaignID", campaignID) :
                new ObjectParameter("CampaignID", typeof(int));
    
            var custCampaignIDParameter = custCampaignID.HasValue ?
                new ObjectParameter("CustCampaignID", custCampaignID) :
                new ObjectParameter("CustCampaignID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Purchase_Result>("SP_Purchase", campaignIDParameter, custCampaignIDParameter);
        }
    }
}
