//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Product
    {
        public int IDProduct { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Size { get; set; }
        public string CampaignName { get; set; }
        public int IDCampaign { get; set; }
        public bool IsActive { get; set; }
        public string Description { get; set; }
        public string SearchName { get; set; }
    }
}
