//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UserAssignMenu
    {
        public int IDUser { get; set; }
        public int IDCampaign { get; set; }
        public int IDMenu { get; set; }
        public string MenuName { get; set; }
        public string RouterLink { get; set; }
        public bool IsActive { get; set; }
    }
}
