//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Purchase
    {
        public long IDPurchase { get; set; }
        public string IDFaktur { get; set; }
        public int IDPartner { get; set; }
        public decimal Amount { get; set; }
        public string IDNumber { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Currency { get; set; }
        public string PartnerName { get; set; }
    }
}
