//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ExpendDetail
    {
        public long IDDetail { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Size { get; set; }
        public int Volume { get; set; }
        public decimal SellPrice { get; set; }
        public decimal SellAmount { get; set; }
        public long IDExpend { get; set; }
        public int IDProduct { get; set; }
        public string IDFaktur { get; set; }
        public int IDSupplier { get; set; }
        public string CurrencyBuy { get; set; }
        public string CurrencySell { get; set; }
        public string CurrencyBuyAmount { get; set; }
        public string CurrencySellAmount { get; set; }
        public System.DateTime Created { get; set; }
        public string StrCreated { get; set; }
        public decimal BuyPrice { get; set; }
        public decimal BuyAmount { get; set; }
    }
}
